#include "param_config.h"

/* GNSS: Latidude, Longitude, Date, Time Speed, Altitude, Course*/
PARAM_DEFINE_REMOTE(gnss_lat, NODE_GNSS, PARAMID_GNSS_LAT, PARAM_TYPE_UINT8, 1, NULL, PM_READONLY, &_gnss_lat, NULL)
PARAM_DEFINE_REMOTE(gnss_lon, NODE_GNSS, PARAMID_GNSS_LON, PARAM_TYPE_FLOAT, 1, NULL, PM_READONLY, &_gnss_lon, NULL)
PARAM_DEFINE_REMOTE(gnss_date, NODE_GNSS, PARAMID_GNSS_DATE, PARAM_TYPE_UINT32, 1, NULL, PM_READONLY, &_gnss_lat, NULL)
PARAM_DEFINE_REMOTE(gnss_time, NODE_GNSS, PARAMID_GNSS_TIME, PARAM_TYPE_UINT32, 1, NULL, PM_READONLY, &_gnss_time, NULL)
PARAM_DEFINE_REMOTE(gnss_speed, NODE_GNSS, PARAMID_GNSS_SPEED, PARAM_TYPE_FLOAT, 1, NULL, PM_READONLY, &_gnss_speed, NULL)
PARAM_DEFINE_REMOTE(gnss_alt, NODE_GNSS, PARAMID_GNSS_ALT, PARAM_TYPE_FLOAT, 1, NULL, PM_READONLY, &_gnss_alt, NULL)
PARAM_DEFINE_REMOTE(gnss_course, NODE_GNSS, PARAMID_GNSS_COURSE, PARAM_TYPE_FLOAT, 1, NULL, PM_READONLY, &_gnss_course, NULL)

/* Temperature measurements from cameras */